apiVersion: v1
kind: Pod
metadata:
  name: tdx-sample-pod
spec:
  containers:
  - name: tdx-sample-pod
    image: docker.io/library/ubuntu:22.04
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - infinity
    resources:
      limits:
        tdx.intel.com/tdx-guest: 1
  nodeSelector:
    intel.feature.node.kubernetes.io/tdx: "true"
