---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - d1c7b6d5.intel.com
  resources:
  - leases
  verbs:
  - get
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - dlbdeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - dlbdeviceplugins/finalizers
  verbs:
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - dlbdeviceplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - dsadeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - dsadeviceplugins/finalizers
  verbs:
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - dsadeviceplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - fpgadeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - fpgadeviceplugins/finalizers
  verbs:
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - fpgadeviceplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - gpudeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - gpudeviceplugins/finalizers
  verbs:
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - gpudeviceplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - iaadeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - iaadeviceplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - qatdeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - qatdeviceplugins/finalizers
  verbs:
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - qatdeviceplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - sgxdeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - sgxdeviceplugins/finalizers
  verbs:
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - sgxdeviceplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - tdxdeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - tdxdeviceplugins/finalizers
  verbs:
  - update
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - tdxdeviceplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fpga.intel.com
  resources:
  - acceleratorfunctions
  - fpgaregions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
